---

  - name: Install Prerequisite Package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    register: result
    until: result is success
    retries: 5
    delay: 10

  - name: enable extras RHEL repository
    yum_repository:
      name: rhui-rhel-7-server-rhui-extras-rpms
      enabled: yes


