---

- name: Install dnsmasq (Darwin)
  homebrew:
    name: dnsmasq
    state: present
  connection: local
  become: no

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf
    dest: /usr/local/etc/dnsmasq.conf
    mode: "u=rw,g=r,o=r"
  connection: local
  become: no

- name: Create dnsmasq launchd configuration
  copy:
    src: /usr/local/opt/dnsmasq/homebrew.mxcl.dnsmasq.plist
    dest: /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
    owner: root
    group: wheel
    mode: "u=rw,g=r,o=r"
  connection: local
  notify: start dnsmasq

- name: Enable dnsmasq launchd configuration
  shell: launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
  connection: local

- name: Make /etc/resolver
  file:
    path: /etc/resolver
    owner: root
    group: wheel
    mode: "u=rwx,g=rx,o=rx"
    state: directory
  connection: local

- name: Configure dnsmasq to serve project web domains
  template:
    src: resolver.j2
    dest: "/etc/resolver/{{ project_name }}"
    owner: root
    group: wheel
    mode: "u=rw,g=r,o=r"
  connection: local

- name: "Create configuration directory of dnsmasq"
  file:
    path: /usr/local/etc/dnsmasq.d
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  connection: local
  become: no

- name: Enable dnsmasq resolver associate
  template:
    src: dnsmasq_project.conf.j2
    dest: "/usr/local/etc/dnsmasq.d/{{ project_name }}"
    mode: "u=rw,g=r,o=r"
  connection: local
  become: no
  notify: restart dnsmasq
